[package]
name = "phototux"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
publish = false
description = "PhotoTux desktop image editor (GUI)"
build = "build.rs"

[[bin]]
name = "phototux"
path = "src/main.rs"

[dependencies]
qtbridge = { workspace = true }
phototux_ui = { workspace = true }
phototux_canvas = { workspace = true }
