/*
 * Regenerate `src/icons.js` from the Phosphor SVGs that ship with the editor.
 *
 *     node build-icons.mjs
 *
 * The websites draw the same glyphs the tool shelf draws, from the same files,
 * so a docs page that labels the Lasso cannot drift from the icon beside it in
 * the app. Icons are inlined as path data rather than fetched as files: they
 * are a few hundred bytes each, they must inherit `currentcolor`, and a
 * sprite sheet would be one more request for no benefit at this size.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "../../../assets/icons/phosphor/regular");

/** Every icon either site draws, by Phosphor stem. Keep sorted. */
const WANTED = [
  "arrow-right",
  "arrow-square-out",
  "arrow-up-right",
  "arrows-out-cardinal",
  "article",
  "book-open-text",
  "caret-down",
  "caret-left",
  "caret-right",
  "caret-up",
  "check",
  "check-circle",
  "circle-dashed",
  "clock-counter-clockwise",
  "code-simple",
  "compass",
  "copy",
  "cpu",
  "crop",
  "cube",
  "download-simple",
  "eraser",
  "eyedropper",
  "floppy-disk",
  "gear",
  "github-logo",
  "graphics-card",
  "hand",
  "hash",
  "image-square",
  "info",
  "keyboard",
  "lasso",
  "layout",
  "lifebuoy",
  "lightning",
  "linux-logo",
  "list",
  "magic-wand",
  "magnifying-glass",
  "mask-happy",
  "monitor",
  "moon",
  "package",
  "paint-brush",
  "palette",
  "plus-circle",
  "polygon",
  "question",
  "rocket-launch",
  "selection",
  "shapes",
  "shield-check",
  "sliders-horizontal",
  "sparkle",
  "squares-four",
  "stack",
  "stamp",
  "sun",
  "terminal-window",
  "text-t",
  "warning",
  "warning-circle",
  "x",
];

/** Pull the geometry out of a Phosphor file, dropping its `<svg>` wrapper. */
function extractBody(svg) {
  const open = svg.indexOf(">", svg.indexOf("<svg"));
  const close = svg.lastIndexOf("</svg>");
  if (open === -1 || close === -1) {
    throw new Error("not an svg");
  }
  return svg
    .slice(open + 1, close)
    .replace(/\s+fill="currentColor"/g, "")
    .trim();
}

const entries = WANTED.map((name) => {
  const svg = readFileSync(join(source, `${name}.svg`), "utf8");
  return `  ${JSON.stringify(name)}: ${JSON.stringify(extractBody(svg))},`;
}).join("\n");

const out = `/*
 * Phosphor Icons 2.1.1 (MIT) — https://phosphoricons.com
 *
 * GENERATED by build-icons.mjs from assets/icons/phosphor/regular. Do not edit
 * by hand: add the stem to WANTED in that script and run it again.
 *
 * Each value is the inside of a 0 0 256 256 <svg>, with the upstream
 * fill="currentColor" stripped so the CSS decides the colour.
 */

/** @type {Record<string, string>} */
export const ICONS = {
${entries}
};

/** Every stem this bundle carries, for the guard test in the sites. */
export const ICON_NAMES = Object.keys(ICONS);
`;

writeFileSync(join(here, "src/icons.js"), out);
console.log(`wrote src/icons.js with ${WANTED.length} icons`);
