[workspace]
resolver = "2"
members = [
    "crates/phototux",
    "crates/phototux-ui",
    "crates/phototux-engine",
    "crates/phototux-gpu",
    "crates/phototux-canvas",
    "crates/phototux-spike-interop",
]
default-members = ["crates/phototux"]

[workspace.package]
edition = "2024"
license = "GPL-3.0-or-later"
version = "0.1.0"
rust-version = "1.87"

[workspace.dependencies]
qtbridge = "0.2.0"
phototux_engine = { path = "crates/phototux-engine" }
phototux_ui = { path = "crates/phototux-ui" }
phototux_canvas = { path = "crates/phototux-canvas" }
phototux_gpu = { path = "crates/phototux-gpu" }
