[package]
name = "phototux_ui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "qtbridge QObjects for PhotoTux UI"

[dependencies]
qtbridge = { workspace = true }
phototux_engine = { workspace = true }
phototux_canvas = { path = "../phototux-canvas" }
phototux_io.workspace = true
percent-encoding.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
