//! CPU-side raster operation scaffolding for PhotoTux.

use common::Point;
use doc_model::{RasterSurface, SelectionBounds, SelectionMask};

/// Brush application mode for round dab raster edits.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BrushApplicationMode {
    /// Paint with the provided RGBA color.
    Paint {
        /// Brush color in straight RGBA8 form.
        color: [u8; 4],
    },
    /// Reduce alpha using the current brush strength.
    Erase,
}

/// CPU-side description of a round brush dab.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct RoundBrushDab {
    /// Dab center in document coordinates.
    pub center: Point,
    /// Brush diameter in pixels.
    pub size: f32,
    /// Hardness in the range `[0.0, 1.0]`.
    pub hardness: f32,
    /// Opacity in the range `[0.0, 1.0]`.
    pub opacity: f32,
    /// Flow in the range `[0.0, 1.0]`.
    pub flow: f32,
    /// Paint or erase behavior.
    pub mode: BrushApplicationMode,
}

/// Pixel-level change generated by an image operation.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct PixelChangeRecord {
    /// Pixel x coordinate.
    pub x: u32,
    /// Pixel y coordinate.
    pub y: u32,
    /// Previous pixel value.
    pub before: [u8; 4],
    /// New pixel value.
    pub after: [u8; 4],
}

/// Lightweight preview data for a round brush.
#[derive(Clone, Debug, PartialEq)]
pub struct BrushPreview {
    /// Brush diameter in pixels.
    pub size: f32,
    /// Brush hardness.
    pub hardness: f32,
    /// Outline points for preview rendering.
    pub outline_points: Vec<Point>,
}

/// Preview state for a committed scale transform.
#[derive(Clone, Debug, PartialEq)]
pub struct ScaleTransformPreview {
    /// Source bounds used for sampling.
    pub source_bounds: SelectionBounds,
    /// Destination bounds after scaling.
    pub target_bounds: SelectionBounds,
    /// Preview raster surface containing the transformed result.
    pub preview_surface: RasterSurface,
}

/// Generate preview geometry for a round brush.
#[must_use]
pub fn brush_preview(size: f32, hardness: f32) -> BrushPreview {
    let radius = (size.max(1.0)) * 0.5;
    let outline_points = (0..32)
        .map(|index| {
            let angle = (index as f32 / 32.0) * std::f32::consts::TAU;
            Point::new(angle.cos() * radius, angle.sin() * radius)
        })
        .collect();

    BrushPreview {
        size: size.max(1.0),
        hardness: hardness.clamp(0.0, 1.0),
        outline_points,
    }
}

/// Apply a single round dab to a raster surface.
#[must_use]
pub fn apply_round_brush_dab(
    surface: &mut RasterSurface,
    dab: RoundBrushDab,
) -> Vec<PixelChangeRecord> {
    let radius = (dab.size.max(1.0)) * 0.5;
    let radius_sq = radius * radius;
    let hardness = dab.hardness.clamp(0.0, 1.0);
    let hard_radius = radius * hardness;
    let hard_radius_sq = hard_radius * hard_radius;
    let soft_range = radius - hard_radius;
    let inverse_soft_range = if soft_range.abs() < f32::EPSILON {
        0.0
    } else {
        1.0 / soft_range
    };
    let opacity_flow = dab.opacity * dab.flow;
    let min_x = (dab.center.x - radius).floor().max(0.0) as u32;
    let min_y = (dab.center.y - radius).floor().max(0.0) as u32;
    let max_x = (dab.center.x + radius)
        .ceil()
        .min((surface.width().saturating_sub(1)) as f32) as u32;
    let max_y = (dab.center.y + radius)
        .ceil()
        .min((surface.height().saturating_sub(1)) as f32) as u32;
    let estimated_capacity = ((max_x - min_x + 1) * (max_y - min_y + 1)) as usize / 2;

    let mut changes = Vec::with_capacity(estimated_capacity.max(1));

    for y in min_y..=max_y {
        for x in min_x..=max_x {
            let dx = (x as f32) + 0.5 - dab.center.x;
            let dy = (y as f32) + 0.5 - dab.center.y;
            let distance_sq = dx * dx + dy * dy;
            let coverage = coverage_for_distance_sq(
                distance_sq,
                radius_sq,
                hard_radius_sq,
                hard_radius,
                inverse_soft_range,
            );
            if coverage <= 0.0 {
                continue;
            }

            let strength = (opacity_flow * coverage).clamp(0.0, 1.0);
            if strength <= 0.0 {
                continue;
            }

            let before = surface.pixel(x, y);
            let after = match dab.mode {
                BrushApplicationMode::Paint { color } => blend_source_over(before, color, strength),
                BrushApplicationMode::Erase => erase_pixel(before, strength),
            };

            if before != after {
                let _ = surface.write_pixel(x, y, after);
                changes.push(PixelChangeRecord {
                    x,
                    y,
                    before,
                    after,
                });
            }
        }
    }

    changes
}

/// Translate the entire raster surface by a pixel delta.
#[must_use]
pub fn translate_surface(
    surface: &mut RasterSurface,
    delta_x: i32,
    delta_y: i32,
) -> Vec<PixelChangeRecord> {
    let before = snapshot_surface(surface);
    let mut after = vec![[0, 0, 0, 0]; before.len()];

    for y in 0..surface.height() {
        for x in 0..surface.width() {
            let target_x = x as i32 + delta_x;
            let target_y = y as i32 + delta_y;
            if target_x < 0
                || target_y < 0
                || target_x >= surface.width() as i32
                || target_y >= surface.height() as i32
            {
                continue;
            }

            after[surface_index(surface.width(), target_x as u32, target_y as u32)] =
                before[surface_index(surface.width(), x, y)];
        }
    }

    apply_surface_snapshot(surface, &before, &after)
}

/// Translate only the currently selected pixels and leave unselected pixels in place.
#[must_use]
pub fn translate_selection(
    surface: &mut RasterSurface,
    selection_mask: &SelectionMask,
    delta_x: i32,
    delta_y: i32,
) -> Vec<PixelChangeRecord> {
    let before = snapshot_surface(surface);
    let mut after = before.clone();

    for y in 0..surface.height() {
        for x in 0..surface.width() {
            if selection_mask.is_selected(x, y) {
                after[surface_index(surface.width(), x, y)] = [0, 0, 0, 0];
            }
        }
    }

    for y in 0..surface.height() {
        for x in 0..surface.width() {
            if !selection_mask.is_selected(x, y) {
                continue;
            }

            let target_x = x as i32 + delta_x;
            let target_y = y as i32 + delta_y;
            if target_x < 0
                || target_y < 0
                || target_x >= surface.width() as i32
                || target_y >= surface.height() as i32
            {
                continue;
            }

            after[surface_index(surface.width(), target_x as u32, target_y as u32)] =
                before[surface_index(surface.width(), x, y)];
        }
    }

    apply_surface_snapshot(surface, &before, &after)
}

/// Create a deterministic nearest-neighbor scale preview for a surface region.
#[must_use]
pub fn preview_scale_surface_nearest(
    surface: &RasterSurface,
    source_bounds: SelectionBounds,
    scale_x: f32,
    scale_y: f32,
) -> ScaleTransformPreview {
    let target_bounds = scaled_bounds(source_bounds, scale_x, scale_y);
    let mut preview_surface = RasterSurface::new(target_bounds.width, target_bounds.height);

    for target_y in 0..target_bounds.height {
        for target_x in 0..target_bounds.width {
            let source_x =
                sample_source_coordinate(source_bounds.width, target_bounds.width, target_x);
            let source_y =
                sample_source_coordinate(source_bounds.height, target_bounds.height, target_y);
            let pixel = surface.pixel(source_bounds.x + source_x, source_bounds.y + source_y);
            if pixel != [0, 0, 0, 0] {
                let _ = preview_surface.write_pixel(target_x, target_y, pixel);
            }
        }
    }

    ScaleTransformPreview {
        source_bounds,
        target_bounds,
        preview_surface,
    }
}

/// Commit a deterministic nearest-neighbor scale transform for a surface region.
#[must_use]
pub fn scale_surface_nearest(
    surface: &mut RasterSurface,
    source_bounds: SelectionBounds,
    scale_x: f32,
    scale_y: f32,
) -> Vec<PixelChangeRecord> {
    let before = snapshot_surface(surface);
    let mut after = before.clone();
    let preview = preview_scale_surface_nearest(surface, source_bounds, scale_x, scale_y);
    let clear_width = source_bounds.width.max(preview.target_bounds.width);
    let clear_height = source_bounds.height.max(preview.target_bounds.height);

    for offset_y in 0..clear_height {
        for offset_x in 0..clear_width {
            let x = source_bounds.x + offset_x;
            let y = source_bounds.y + offset_y;
            if x >= surface.width() || y >= surface.height() {
                continue;
            }
            after[surface_index(surface.width(), x, y)] = [0, 0, 0, 0];
        }
    }

    for target_y in 0..preview.target_bounds.height {
        for target_x in 0..preview.target_bounds.width {
            let dest_x = preview.target_bounds.x + target_x;
            let dest_y = preview.target_bounds.y + target_y;
            if dest_x >= surface.width() || dest_y >= surface.height() {
                continue;
            }

            after[surface_index(surface.width(), dest_x, dest_y)] =
                preview.preview_surface.pixel(target_x, target_y);
        }
    }

    apply_surface_snapshot(surface, &before, &after)
}

fn scaled_bounds(source_bounds: SelectionBounds, scale_x: f32, scale_y: f32) -> SelectionBounds {
    let target_width = ((source_bounds.width as f32) * scale_x.clamp(0.01, 64.0))
        .round()
        .max(1.0) as u32;
    let target_height = ((source_bounds.height as f32) * scale_y.clamp(0.01, 64.0))
        .round()
        .max(1.0) as u32;

    SelectionBounds::new(
        source_bounds.x,
        source_bounds.y,
        target_width,
        target_height,
    )
}

fn sample_source_coordinate(source_len: u32, target_len: u32, target_index: u32) -> u32 {
    if target_len <= 1 || source_len <= 1 {
        return 0;
    }

    (((target_index as f32) * source_len as f32) / target_len as f32)
        .floor()
        .clamp(0.0, source_len.saturating_sub(1) as f32) as u32
}

fn snapshot_surface(surface: &RasterSurface) -> Vec<[u8; 4]> {
    let mut snapshot = Vec::with_capacity((surface.width() * surface.height()) as usize);
    for y in 0..surface.height() {
        for x in 0..surface.width() {
            snapshot.push(surface.pixel(x, y));
        }
    }
    snapshot
}

fn apply_surface_snapshot(
    surface: &mut RasterSurface,
    before: &[[u8; 4]],
    after: &[[u8; 4]],
) -> Vec<PixelChangeRecord> {
    let mut changes = Vec::new();

    for y in 0..surface.height() {
        for x in 0..surface.width() {
            let index = surface_index(surface.width(), x, y);
            if before[index] == after[index] {
                continue;
            }

            let _ = surface.write_pixel(x, y, after[index]);
            changes.push(PixelChangeRecord {
                x,
                y,
                before: before[index],
                after: after[index],
            });
        }
    }

    changes
}

fn surface_index(width: u32, x: u32, y: u32) -> usize {
    (y as usize) * (width as usize) + (x as usize)
}

fn coverage_for_distance_sq(
    distance_sq: f32,
    radius_sq: f32,
    hard_radius_sq: f32,
    hard_radius: f32,
    inverse_soft_range: f32,
) -> f32 {
    if distance_sq > radius_sq {
        return 0.0;
    }

    if distance_sq <= hard_radius_sq || inverse_soft_range == 0.0 {
        return 1.0;
    }

    let distance = distance_sq.sqrt();
    1.0 - ((distance - hard_radius) * inverse_soft_range)
}

fn blend_source_over(dst: [u8; 4], src: [u8; 4], strength: f32) -> [u8; 4] {
    let src_alpha = ((src[3] as f32) / 255.0) * strength;
    let dst_alpha = (dst[3] as f32) / 255.0;
    let out_alpha = src_alpha + dst_alpha * (1.0 - src_alpha);
    if out_alpha <= 0.0 {
        return [0, 0, 0, 0];
    }

    let mut out = [0; 4];
    for channel in 0..3 {
        let src_value = (src[channel] as f32) / 255.0;
        let dst_value = (dst[channel] as f32) / 255.0;
        let out_value =
            (src_value * src_alpha + dst_value * dst_alpha * (1.0 - src_alpha)) / out_alpha;
        out[channel] = (out_value.clamp(0.0, 1.0) * 255.0).round() as u8;
    }
    out[3] = (out_alpha * 255.0).round() as u8;
    out
}

fn erase_pixel(dst: [u8; 4], strength: f32) -> [u8; 4] {
    let keep = (1.0 - strength).clamp(0.0, 1.0);
    [
        ((dst[0] as f32) * keep).round() as u8,
        ((dst[1] as f32) * keep).round() as u8,
        ((dst[2] as f32) * keep).round() as u8,
        ((dst[3] as f32) * keep).round() as u8,
    ]
}

#[cfg(test)]
mod tests {
    use super::{BrushApplicationMode, RoundBrushDab, apply_round_brush_dab, brush_preview};
    use common::Point;
    use doc_model::RasterSurface;

    #[test]
    fn paint_dab_changes_surface_pixels() {
        let mut surface = RasterSurface::new(64, 64);

        let changes = apply_round_brush_dab(
            &mut surface,
            RoundBrushDab {
                center: Point::new(32.0, 32.0),
                size: 12.0,
                hardness: 1.0,
                opacity: 1.0,
                flow: 1.0,
                mode: BrushApplicationMode::Paint {
                    color: [255, 0, 0, 255],
                },
            },
        );

        assert!(!changes.is_empty());
        assert_ne!(surface.pixel(32, 32), [0, 0, 0, 0]);
    }

    #[test]
    fn eraser_reduces_alpha() {
        let mut surface = RasterSurface::new(64, 64);
        let _ = surface.write_pixel(32, 32, [255, 255, 255, 255]);

        let changes = apply_round_brush_dab(
            &mut surface,
            RoundBrushDab {
                center: Point::new(32.0, 32.0),
                size: 8.0,
                hardness: 1.0,
                opacity: 1.0,
                flow: 0.5,
                mode: BrushApplicationMode::Erase,
            },
        );

        assert!(!changes.is_empty());
        assert!(surface.pixel(32, 32)[3] < 255);
    }

    #[test]
    fn brush_preview_produces_outline_points() {
        let preview = brush_preview(20.0, 0.75);

        assert_eq!(preview.outline_points.len(), 32);
        assert_eq!(preview.size, 20.0);
    }
}
